;;; $DOOMDIR/theme/dark.el -*- lexical-binding: t; -*-
(require 'doom-themes)

(def-doom-theme theme-dark
  "My custom dark theme"
  ((bg        '(palette0F "black"       "black"))
   (bg-alt    '(palette0D "black"       "black"))
   (base0     '(palette0F "black"       "black"))
   (base1     '(palette0D "brightblack" "brightblack"))
   (base2     '(palette0B "brightblack" "brightblack"))
   (base3     '(palette09 "brightblack" "brightblack"))
   (base4     '(palette08 "brightblack" "brightblack"))
   (base5     '(palette07 "brightblack" "brightblack"))
   (base6     '(palette05 "brightblack" "brightblack"))
   (base7     '(palette03 "brightblack" "brightblack"))
   (base8     '(palette01 "white"       "white"))
   (fg        '(palette00 "white"       "white"))
   (fg-alt    '(palette02 "white"       "white"))

   (grey                base4)
   (red                 '(palette17 "red" "red"))
   (orange              '(palette27 "brightred" "brightred"))
   (green               '(palette47 "green" "green"))
   (teal                '(palette47 "brightgreen" "brightgreen"))
   (yellow              '(palette34 "yellow" "yellow"))
   (blue                '(palette67 "brightblue" "brightblue"))
   (dark-blue           '(palette69 "blue" "blue"))
   (magenta             '(palette75 "brightmagenta" "brightmagenta"))
   (violet              '(palette77 "magenta" "magenta"))
   (cyan                '(palette55 "brightcyan" "brightcyan"))
   (dark-cyan           '(palette55 "cyan" "cyan"))

   ; These are the "universal syntax classes" that doom-themes establishes.
   ; These *must* be included in every doom themes, or your theme will throw an
   ; error, as they are used in the base theme defined in doom-themes-base.
   (highlight    blue)
   (vertical-bar base0)
   (selection    base1)
   (builtin      magenta)
   (comments     base5)
   (doc-comments base4)
   (constants    violet)
   (functions    cyan)
   (keywords     blue)
   (methods      violet)
   (operators    magenta)
   (type         yellow)
   (strings      green)
   (variables    base8)
   (numbers      orange)
   (region       base3)
   (error        red)
   (warning      yellow)
   (success      green)
   (vc-modified  yellow)
   (vc-added     green)
   (vc-deleted   red)))

(provide 'dark '(theme-dark))
