;;; mylight-theme.el -*- lexical-binding: t; no-byte-compile: t; -*-
(require 'doom-themes)
(require 'mypalette)

(def-doom-theme mylight
  "My custom light theme"
  ((fg        (-map 'eval '(palette0F "black"       "black")))
   (fg-alt    (-map 'eval '(palette0D "black"       "black")))
   (base8     (-map 'eval '(palette0F "black"       "black")))
   (base7     (-map 'eval '(palette0D "brightblack" "brightblack")))
   (base6     (-map 'eval '(palette0B "brightblack" "brightblack")))
   (base5     (-map 'eval '(palette09 "brightblack" "brightblack")))
   (base4     (-map 'eval '(palette08 "brightblack" "brightblack")))
   (base3     (-map 'eval '(palette07 "brightblack" "brightblack")))
   (base2     (-map 'eval '(palette05 "brightblack" "brightblack")))
   (base1     (-map 'eval '(palette03 "brightblack" "brightblack")))
   (base0     (-map 'eval '(palette01 "white"       "white")))
   (bg        (-map 'eval '(palette00 "white"       "white")))
   (bg-alt    (-map 'eval '(palette02 "white"       "white")))

   (grey                base4)
   (red                 (-map 'eval '(palette17 "red" "red")))
   (orange              (-map 'eval '(palette26 "brightred" "brightred")))
   (green               (-map 'eval '(palette4B "green" "green")))
   (teal                (-map 'eval '(palette4B "brightgreen" "brightgreen")))
   (yellow              (-map 'eval '(palette35 "yellow" "yellow")))
   (blue                (-map 'eval '(palette68 "brightblue" "brightblue")))
   (dark-blue           (-map 'eval '(palette6C "blue" "blue")))
   (magenta             (-map 'eval '(palette7A "brightmagenta" "brightmagenta")))
   (violet              (-map 'eval '(palette76 "magenta" "magenta")))
   (cyan                (-map 'eval '(palette56 "brightcyan" "brightcyan")))
   (dark-cyan           (-map 'eval '(palette57 "cyan" "cyan")))

   ; These are the "universal syntax classes" that doom-themes establishes.
   ; These *must* be included in every doom themes, or your theme will throw an
   ; error, as they are used in the base theme defined in doom-themes-base.
   (highlight    blue)
   (vertical-bar base0)
   (selection    base1)
   (builtin      magenta)
   (comments     base6)
   (doc-comments base5)
   (constants    violet)
   (functions    magenta)
   (keywords     dark-blue)
   (methods      violet)
   (operators    magenta)
   (type         teal)
   (strings      green)
   (variables    fg-alt)
   (numbers      orange)
   (region       base1)
   (error        red)
   (warning      yellow)
   (success      green)
   (vc-modified  yellow)
   (vc-added     green)
   (vc-deleted   red))

  ((lsp-face-highlight-textual :background base1 :foreground fg-alt :distant-background bg-alt)
   (cursor :background palette67)
   (doom-modeline-evil-normal-state :foreground palette47)
   (doom-modeline-project-dir       :foreground palette48 :weight 'bold)
   (doom-modeline-info              :foreground palette48 :weight 'bold)
   (diff-removed                    :foreground red :background palette10)
   (diff-indicator-removed          :foreground red :background palette11)
   (magit-diff-removed              :foreground red :background palette10)
   (magit-diff-our-highlight        :foreground red :background palette11 :weight 'bold)
   (magit-diff-removed-highlight    :foreground red :background palette11 :weight 'bold)
   (diff-refine-removed             :foreground bg-alt :background red :weight 'bold)
   (vterm-color-black               :foreground base6 :background base5)))
